spring:
  application:
    name: spring-eureka-client

server:
  port: 8989

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8084/spring-eureka-server
  instance:
    preferIpAddress: true    